/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{jsx,tsx,js,ts}',
    './src/pages/**/*.{jsx,tsx,js,ts}',
    './src/pages/**/*.jsx',
    './index.html',
    './**/*.html'
  ],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    // 明示的に色を指定
    'bg-blue-50',
    'bg-blue-100',
    'bg-blue-500',
    'bg-blue-600',
    'from-blue-50',
    'to-blue-100',
    'border-blue-500',
    'text-blue-600',
    'hover:bg-blue-600',
    
    'bg-purple-50',
    'bg-purple-100',
    'bg-purple-500',
    'bg-purple-600',
    'from-purple-50',
    'to-purple-100',
    'border-purple-500',
    'hover:bg-purple-600',
    
    'bg-green-50',
    'bg-green-100',
    'bg-green-500',
    'bg-green-600',
    'from-green-50',
    'to-green-100',
    'border-green-500',
    'hover:bg-green-600',
    
    'from-indigo-200',
    'to-cyan-200',
    'bg-gradient-to-br',
    'bg-gradient-to-r',
    'bg-white',
    'text-gray-600',
    'text-gray-800',
    'text-green-600',
    'text-red-600',
    'shadow-lg',
    'rounded-xl',
    'rounded-lg',
    'border-l-4',
    'border-t',
    'border-gray-300',
    'min-h-screen',
    'flex',
    'items-center',
    'justify-center',
    'justify-between',
    'w-full',
    'max-w-lg',
    'p-4',
    'p-8',
    'px-3',
    'py-2',
    'mb-1',
    'mb-2',
    'mb-6',
    'mt-4',
    'my-6',
    'text-sm',
    'text-xl',
    'text-2xl',
    'font-bold',
    'font-semibold',
    'font-medium',
    'transition-colors',
    'animate-bounce',
    'space-y-4'
  ]
}

